name: Checkov IaC Scan

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkov on Terraform only
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          framework: terraform
          soft_fail: true
          quiet: true
