name: gitleaks

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - "feature/**"
      - "feature-*"
      - "fix/**"
      - "bugfix/**"
      - "hotfix/**"

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
