name: Send Approved PR to SNOW

on:
  pull_request_review:
    types: [submitted]

jobs:
  send:
    if: github.event.review.state == 'approved'

    runs-on: ubuntu-latest

    steps:
      - name: Send PR to SNOW
        run: |
          echo "Sending PR to SNOW..."

          curl -X POST \
          -u "${{ secrets.SN_API_USER }}:${{ secrets.SN_API_PASSWORD }}" \
          -H "Content-Type: application/json" \
          -d '{
            "pr_number": "${{ github.event.pull_request.number }}",
            "repo": "${{ github.repository }}",
            "source_branch": "${{ github.event.pull_request.head.ref }}",
            "target_branch": "${{ github.event.pull_request.base.ref }}",
            "pr_url": "${{ github.event.pull_request.html_url }}"
          }' \
          ${{ secrets.SN_INSTANCE_URL }}/api/x_vbo_ghgov/pull-request-approved
